### ISSUE TITLE
Initialize landing page with Next.js

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#1]
- Set up the project frontend using Next.js. [GUIDE ](https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup)
- Initialize the frontend with Next.js as the starting point.
- Add a Markdown file with instructions to run the landing.
- If you need the logo in .svg you can request it by telegram or any other query.

Technical Implementation:

Next.js 14
TypeScript
[TailwindCSS](https://tailwindcss.com/)
[shadcn/ui](https://ui.shadcn.com/)
[Class Variance Authority](https://cva.style/docs)
[Radix UI](https://www.radix-ui.com/)
[Lucide](https://lucide.dev/icons/)
(If you have another better technological implementation, propose it.)

The goal is to initially invite small businesses to implement Paystell as a payment method in their stores. Each business will have a customized payment gateway with its own branding, allowing them to set transaction amounts and accept payments in their local currency equivalent.

**Comment by NueloSE** [comment]
@MPSxDev I would love to be a part of this awesome project kindly assign me this task

## Psuedo approach:
1. project setup and initial configuration
`npx create-next-app@latest paystell-frontend --typescript --tailwind --eslint`
`cd paystell-frontend`

**Comment by abdegenius** [comment]
I can comfortably handle this issues, i will setup an easy to use and maintain frontend build

**Comment by wheval** [comment]
Can I take care of this issue?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by starknetbrother** [comment]
Could I be assigned to this?

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by Michaelkingsdev** [comment]
Can I take this issue? I use nextjs often and i know how to tackle this issue.

**Comment by DiegoB1911** [comment]
I am a Full Stack Developer with two years of experience, primarily working with Next.js. Currently, I am a member of Dojo Coding, where I am learning about Cairo and Web3 technologies.

To solve this issue, I would take the following steps:

1. Set up the Project Environment: Initialize the project and configure the necessary tools and dependencies.
2. Implement the Landing Page: Design and develop the landing page, ensuring it meets all requirements.
3. Create Markdown Documentation: Document setup instructions and usage details for easy collaboration.
4. Verify Changes and Document Them: Test the implementation thoroughly, validate the changes, and update the documentation as needed.

**Comment by MullerTheScientist** [comment]
Please Can I address this issue

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


I will instakking next. js 14: using the documentation site and adding tailwind css, shadcnui, class variance authority, radix ui, lucide base on the suggestion will ask about what other thing you want to use in the project and suggest it

will be glad to work on this 
Thanks

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by brolag** [comment]
Hi, I have around 10 years of experience working with web technologies and I already did something like this for another project. https://github.com/KaizeNodeLabs/SafeSwap/pull/7

A can add not only a boilerplate with Next.js but provide an extra set of tools for making it scalable and well organized, please take a look at my previous work and let me know if I can help.

https://github.com/Vagabonds-Labs/cofiblocks

**Comment by jedstroke** [comment]
Could I try solving this?

**Comment by sandragcarrillo** [comment]
I would love to contribute to this issue, I have experience as a frontend developer creating protocols websites.
