### ISSUE TITLE
Create Frequently Asked Questions Section

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#10]
## 📄 Issue Description
Implement the "Frequently Asked Questions" (FAQ) section of the landing page based on the Figma design. This section provides answers to common user queries in an organized and user-friendly layout.

## 🔍 Steps

1. Analyze the Figma design for the FAQ section.
2. Review the structure of existing components for alignment.
3. Create a reusable accordion component for questions and answers.
4. Style the component to match the theme of the page.
5. Test for responsiveness and accessibility across devices.

## ✅ Acceptance Criteria

- The FAQ section matches the Figma design.
- Questions and answers are presented in a collapsible accordion format.
- Section is fully responsive and accessible.
- Components must be separated in their individual folder per section. In this case, use the faq folder in components.

## 🌎 References
[Figma Design](https://github.com/PayStell/paystell-landing/blob/main/landingPage.md)

**Comment by MarcusDavidG** [comment]
May I take care of this? with my solid experience with web3 frontend design and knowledge of how smart contracts work, Handling this should not be an issue

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by mimisavage** [comment]
Can I take this from here?

**Comment by NueloSE** [comment]
Can I be assigned to this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by JamesVictor-O** [comment]
GM. I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I'm confident in implementing the 'Frequently Asked Questions' (FAQ) section of the landing page based on the Figma design, using Shadcn UI and Tailwind CSS, with an Eth of 24 hours

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/ Let me try this one

**Comment by codeZe-us** [comment]
Please can I take on this task?

**Comment by psychemist** [comment]
Hello, Paystell maintainers!!

I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites, and decentralized applications. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

Here’s my plan for fixing this iisue:

- Design the FAQ section using a collapsible accordion format to display questions and answers clearly.
- Create a reusable accordion component within the faq folder in components to handle the questions and answers dynamically.
- Style the accordion to match the Figma design and the overall theme of the landing page.
- Test the section for responsiveness and accessibility to ensure it works seamlessly across all devices and screen sizes.
- Ensure the FAQ section is intuitive, easy to navigate, and matches the Figma design specifications.

These steps will ensure a clean, user-friendly FAQ section that’s fully functional and accessible to all users.


I aim to complete this task within 24 hours being assigned and setting up my development environment, with my first pull request submitted before 8 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail.
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.

**Comment by davedumto** [comment]
Hi, my name is David, and I am skilled in JavaScript, TypeScript, Tailwind CSS, and ShadCN.
To implement this feature, I plan to analyze the Figma design to ensure pixel-perfect alignment, create a reusable accordion component for the FAQs, and style it using Tailwind CSS to match the page's theme. I will also ensure responsiveness and accessibility for a seamless user experience across devices.
ETA: 3 days.
Thank you for considering my application!

**Comment by DanielEmmanuel1** [comment]
Can I handle this task?

**Comment by akintola4** [comment]
I confirmed the design in the figma file and i'm sure i can do it within the estimated time given to me and I have good track record of building frontend website i have them on my twitter and various repos in my github this is an example (https://ooido-kc4l.vercel.app/)

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will implement the Frequently Asked Questions (FAQ) section of the landing page following the Figma design. This will include creating a reusable accordion component for displaying questions and answers in a collapsible format, styled to match the page theme. I will ensure the section is responsive and accessible across all devices, organizing the components in a dedicated FAQ folder within the components directory. The section will be fully aligned with the Figma design. I estimate completing this task in 2-3 days.

**Comment by TheSQLguy** [comment]
Here I will analyze the Figma design for the FAQ section and create a reusable accordion component to display questions and answers. The component will be styled according to the page's theme, and I will ensure it is fully responsive and accessible across devices. The FAQ section will be placed in the faq folder under components for proper organization.

**Comment by Supa-mega** [comment]
Can I tackle this one?

**Comment by emmz3230** [comment]
Can I attempt this issue?

Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will interpret the design well to a well mannered layout by using my front-end skill

**Comment by kcmikee** [comment]
I am kcmikee, a frontend developer with 4+ years of experience working with React, Next.js, and TypeScript. I am a graduate of Web3bridge Africa, where I got to dive deep into blockchain development and contribute to some cool web3 projects. I have also made significant contributions to open-source projects and am eager to bring that expertise to this project.
My approach to this task will include:
1. Reviewing the project structure, Figma designs, and any relevant files.
2. Implementing the FAQ section, ensuring it adheres to the application's color scheme and branding.
3. Make sure it doesn't affect the application's performance

Estimated Time (ET): 1 day.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Cbiux** [comment]
I’m excited about the opportunity to work on the "Frequently Asked Questions" section. Designing interfaces that are clear and helpful for users is something I truly enjoy, and this section plays a key role in building trust and addressing questions effectively.

I can bring a well-structured, visually appealing, and user-friendly design, ensuring the FAQs directly connect with users’ needs. I’m highly motivated to contribute to this project’s success with my passion for design and development focused on user experience.

Looking forward to the chance to collaborate on this issue. Thank you for considering me!
