### ISSUE TITLE
Create Footer Section

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#11]
## 📄 Issue Description
Implement the Footer section of the landing page based on the Figma design. This section includes navigation links, social media icons, and a copyright notice.

## 🔍 Steps
Analyze the Figma design for the Footer section.
Review the structure of existing components for alignment.
Create a reusable component for the Footer.
Add navigation links and ensure they are functional (dummy links for now).
Include social media icons.
Add a copyright notice styled as per the design.
Validate responsiveness and alignment across devices.

## ✅ Acceptance Criteria

- The Footer matches the Figma design.
- Navigation links and social media icons are functional.
- The section is fully responsive and accessible.
- Components must be separated in their individual folder per section. In this case, use the footer folder in components.

## 🌎 References
[Figma Design](https://github.com/PayStell/paystell-landing/blob/main/landingPage.md)

**Comment by MarcusDavidG** [comment]
I’m interested in this one.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by Michaelkingsdev** [comment]
May I handle this issue?

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by JamesVictor-O** [comment]
GM. I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I'm confident in creating the 'Footer Section'  section according to the Figma design, using Shadcn UI and Tailwind CSS. Eth of 1 hour

**Comment by codeZe-us** [comment]
Please can I take on this task

**Comment by psychemist** [comment]
Hello, Paystell maintainers!!

I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites, and decentralized applications. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

To implement the Footer section based on the Figma design, here’s what I will do:

- Create a reusable Footer component in the footer folder inside the components directory, following the layout from the Figma design.
- Add navigation links with dummy URLs for now, ensuring they align and function as placeholders.
Include social media icons in line with the design, ensuring they are clickable and linked (dummy links for now).
- Add a copyright notice styled according to the design, ensuring the text and layout are in line with the overall aesthetic.
- Test for responsiveness and alignment across different devices to ensure the footer adapts well to various screen sizes, matches the Figma design, and is fully accessible.

I aim to complete this task within 30 hours of being assigned and setting up my development environment, with my first pull request submitted before 10 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail & .
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.

**Comment by akintola4** [comment]
i went through the design in the figma file and I'm sure i can deliver this within the estimated time given by the maintainer

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by salazarsebas** [comment]
Hi PayStell,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Analyze the Figma design for the Footer section.
- Review the structure of the existing components to align them.
- Create a reusable component for the footer.
- Add navigation links and make sure they are functional (dummy links for now).
- Include social media icons.
- Add a copyright notice with the style of the design.
- Validate responsiveness and alignment between devices.
- Verify that the design is aesthetically pleasing and matches the figma.
- Send a pr pending feedback.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will implement the Footer section of the landing page based on the Figma design. This includes creating a reusable component with navigation links, social media icons, and a copyright notice. I will ensure that the navigation links are functional (with dummy links for now) and the section is fully responsive and aligned across devices. The components will be organized in a footer folder under the components directory. I will validate accessibility and responsiveness and ensure the design matches the Figma specification. I estimate completing this task in 2-3 days.

**Comment by Prosper1218** [comment]
I am Prosper Williams, a software developer with 3+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript.. I have made contributions to projects and i look forward to contributing to this. i also have experience working with a team. My approach to this will be to

1- Review the project structure, figma link and necessary files
2- Build out the footer component. 
3- make sure that design comes out as it is in the figma file.

ET: 2 days

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I would first analyze the Figma design to understand the layout and structure of the Footer section. Then, I would create a reusable Footer component in the footer folder within the components directory. I would add the navigation links with dummy URLs for now and include social media icons, making sure they match the design. I’d also include a copyright notice styled according to the Figma design. I would ensure the footer is responsive, checking its alignment across different screen sizes, and confirm that it is fully accessible. Finally, I would organize the components in individual folders as per the structure in the design. ETA 2-3 days.

**Comment by TheSQLguy** [comment]
So, i am new to open source and want to contribute.
Here I will break down the Figma design for the Footer section and create a reusable Footer component. That will include navigation links with dummy links for now, social media icons, and a copyright notice styled according to the design. I will make sure the Footer is fully responsive, accessible, and fits the design across devices with the components organized in the footer folder under components.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will Implement the Footer section of the landing page following the Figma design, ensuring it includes navigation links, social media icons, and a copyright notice. First, analyze the Figma design for proper structure and review existing components for consistency. Create a reusable Footer component, adding navigation links (with dummy links for now) and social media icons as specified in the design.

**Comment by Supa-mega** [comment]
I’d like to help with this.

**Comment by emmz3230** [comment]
Is it okay if I take this?
Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

i will intrepret the design by using the social media icons used and the font in the design and importing other component hereby making it responsive.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe (A Defi startup built on Lisk)
• Scaffold-ETH
• BuidlGuidl
I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by Gifftybabe** [comment]
Hello, I am Gift and 
I am excited to apply for the Footer section implementation task for the landing page, demonstrating a comprehensive approach to meeting the project's requirements.

##Proposed Implementation Strategy

- Thoroughly review the Figma design to ensure pixel-perfect implementation
- Create a modular, reusable Footer component located in `src/components/footer/`
- Ensure component follows best practices for React component design

### 2. Component Implementation Details
#### Footer Component Breakdown
- Navigation Links Section
  - Create a dedicated navigation links sub-component
  - Implement dummy links with proper routing structure
  - Ensure accessibility with semantic HTML and ARIA attributes

- Social Media Icons Section
  - Design a flexible social media icon component
  - Use SVG or icon library for crisp, scalable icons
  - Add hover and focus states for improved interactivity

- Copyright Notice
  - Dynamic copyright text with current year
  - Styled according to Figma design specifications

### 3. Responsiveness and Accessibility
- Implement mobile-first responsive design
- Use CSS Flexbox/Grid for flexible layouts
- Ensure WCAG 2.1 AA compliance
- Test across multiple device sizes and screen readers

### 4. Technical Approach
- Framework: React
- Styling: CSS Modules or Tailwind CSS
- State Management: Minimal, component-level state
- Performance optimization techniques

### 5. Quality Assurance
- Implement unit tests for component rendering
- Cross-browser compatibility testing
- Lighthouse performance and accessibility audit

## Proposed Timeline
- Design Analysis: 2 hours
- Initial Implementation: 4-5 hours
- Refinement and Testing: 2-3 hours
- Total Estimated Time: 8-10 hours

## Commitment
I am fully committed to delivering a high-quality, pixel-perfect Footer component that meets all specified requirements and enhances the overall user experience of the landing page.

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Ibinola** [comment]
## I'm Michael Ibinola
 
I'm a frontend developer with experience using React, Next.js and TypeScript. I’m a first time contributor to PayStell, and would love to tackle this issue. 

I’d love to work on this task.
 
 
 ## Problem
Implement the Footer section of the landing page. 
 
 ## Solution
Create a reusable component for the Footer, add the navigation links, include social media icons, add the copyright notice and ensure responsiveness across all devices.

**Comment by SimplementeCao** [comment]
Hi, I'm Leandro, Front-end developer.
I would solve the issue first by reviewing the design of the image and adjusting to the development pattern by components to maintain consistency and scalability of the project, I also make sure it is responsive.

Estimated delivery time: 10 hours.

I have previously collaborated on other projects such as:
Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenges Factory
Starkane

Can I work on this issue?

**Comment by caxtonacollins** [comment]
May I pick this up?

**Comment by SimplementeCao** [comment]
Hi @MPSxDev! if there is still no one working on this issue I would like to do it !
