### ISSUE TITLE
Create Testimonial Section

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#6]
## 📄 Issue Description
Build the testimonial section based on the Figma design. This section will display client testimonials in a visually appealing layout.

## 🔍 Steps

1. Review the Figma design for the testimonial section.
2. See how the components of the current landing page are implemented and created.
3. Create a React component to render testimonials dynamically.
4. Add interactive features using Radix UI.
5. Ensure the section supports dynamic data.

## ✅ Acceptance Criteria

- The testimonial section matches the Figma design.
- Testimonials are rendered dynamically.
- Section is fully responsive and accessible.
- Interactive elements work as expected.
- Components must be separated in their individual folder per section. In this case, use the testimonial folder in components.

## 🌎 References
[Figma Design](https://github.com/PayStell/paystell-landing/blob/main/landingPage.md)

## 📜 Additional Notes
Consider making the testimonial data reusable for future sections or components.

**Comment by MarcusDavidG** [comment]
May I take care of this?

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by mimisavage** [comment]
Could I try solving this?

**Comment by josephchimebuka** [comment]
Can I tackle this one? Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

**Comment by Michaelkingsdev** [comment]
Can I take this issue?

**Comment by NueloSE** [comment]
Can I take this from here?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by psychemist** [comment]
Hello, Paystell maintainers!!

I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites, and decentralized applications. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

I will tackle this issue using these steps:

- Take a close look at the Figma design to nail the layout, styling, and structure of the testimonial section.

- Check out how other sections of the landing page are built to keep things consistent.

- Create a React component to dynamically display testimonials, making it easy to update in the future.

- Add interactive features with Radix UI, like carousels or modals, to make the section engaging.

- Style the section with responsive CSS and test for accessibility to ensure it works seamlessly across devices.

- Organize the component in the testimonial folder in the components directory for clean, maintainable code.

I aim to complete this task within 24 hours being assigned and setting up my development environment, with my first pull request submitted before 8 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by codeZe-us** [comment]
Please can I take on this task?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail.
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.
2days

**Comment by DanielEmmanuel1** [comment]
Would love to tackle this!

**Comment by davedumto** [comment]
Hi, my name is David, and I am skilled in JavaScript, TypeScript, Tailwind CSS, and ShadCN.
For the testimonial section, I plan to analyze the Figma design to create a visually appealing layout. I will build a React component that dynamically renders testimonials, incorporating interactive features with Radix UI. Additionally, I will ensure the section is fully responsive, accessible, and supports dynamic data, placing the components in the dedicated testimonial folder.
ETA: 3 days.
Thank you for considering my application!

**Comment by jahrulezfrancis** [comment]
I would love to be assigned to this issue. I’ll build the testimonial section to align with the Figma design, ensuring dynamic rendering of testimonials and interactive features with Radix UI. The section will be fully responsive, accessible, and support dynamic data. Components will be well structured in a testimonial folder for reusability and maintainability. I can complete this within 24 to 36 hours.

**Comment by Agbeleshe** [comment]
Hello, I would love to solve this issue. I will analyze the Figma design to understand the layout, styling, and interactive requirements for the testimonial section. Using a `components/testimonial` folder, I will create a React component to dynamically render testimonials from a data source. Interactive features, such as sliders or navigation, will be implemented using Radix UI to enhance user experience. I will ensure the section is fully responsive and accessible on all devices while maintaining alignment with the overall design of the landing page. Additionally, the testimonial data will be structured for reusability in future components or pages.
My estimated time to complete this task is 1–24 hours.

**Comment by TheSQLguy** [comment]
I am new to open source and want to contribute
So I will code review the Figma testimonial section and create a dynamic testimonial component in React. Radix UI will be integrated into the section to make all its interactive features more functional and functional. The section shall be responsive and accessible while its component shall be held within the testimonial folder of components for proper compartmentalization.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will build the testimonial section for the landing page based on the Figma design, ensuring a visually appealing layout to display client testimonials. Start by reviewing the Figma design for the section and examining the structure of other components on the landing page. Create a React component that dynamically renders testimonials, incorporating interactive features using Radix UI for improved user interaction. Ensure the section supports dynamic data and renders appropriately based on the provided information. The section must be fully responsive and accessible across devices, and interactive elements should function as expected. Organize the component within a testimonial folder in the components directory to maintain clean structure and modularity.

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by emmz3230** [comment]
Would love to tackle this!

Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will make the testimonial appealing according to the Figma design and will ask the maintainer if animation for slider is needed and as add it as an extra.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe (A Defi startup built on Lisk)
• Scaffold-ETH
• BuidlGuidl
I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by therealemino** [comment]
Is this issue still available?

**Comment by caxtonacollins** [comment]
Can I try solving this issue?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in building scalable front-end components and delivering projects aligned with design systems. I’ve contributed to multiple projects, including modular and reusable UI implementations.

To tackle this issue:

I’ll build the testimonial section based on the Figma design, ensuring it matches the current landing page style.
Create a reusable React component for dynamic testimonial rendering and integrate interactive features using Radix UI.
Ensure the section is responsive, accessible, and structured in a testimonial folder for modularity.
ETA: 12-48 hours. Feel free to reach out via Telegram
