### ISSUE TITLE
Create How it Works Section

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#7]
## 📄 Issue Description
Implement the How it Works section of the landing page based on the Figma design. This section showcases three stages: Register & Setup, Create and ShareLink, and Receive Payments.

## 🔍 Steps

1. Analyze the Figma design for the "How it Works" section.
2. See how the components of the current landing page are implemented and created.
3. Create a reusable component for each stage within the "How it Works" section.
4. Add appropriate icons or visuals for each stage.
5. Ensure the layout is responsive and visually consistent.

## ✅ Acceptance Criteria

- The "How it Works" section matches the Figma design.
- Each stage (Register & Setup, Create and ShareLink, Receive Payments) is clearly represented with corresponding visuals or icons.
- Section is fully responsive and accessible.
- Components must be separated in their individual folder per section. In this case, use the how-it-works folder in components.

## 🌎 References
[Figma Design](https://github.com/PayStell/paystell-landing/blob/main/landingPage.md)

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by MarcusDavidG** [comment]
Can I take care of this issue?

**Comment by kcmikee** [comment]
Is it okay if I tackle this?

**Comment by mimisavage** [comment]
May I take care of this?

**Comment by josephchimebuka** [comment]
Can I take this issue? Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

**Comment by Michaelkingsdev** [comment]
I'd love to give this a go.

**Comment by NueloSE** [comment]
I’d like to work on this.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by JamesVictor-O** [comment]
GM. I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I'm confident in creating the 'Create How it Works Section' section of the landing page based on the Figma design, using Shadcn UI and Tailwind CSS. Eth of 2 hours

**Comment by psychemist** [comment]
Hello, Paystell maintainers!!

I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites, and decentralized applications. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

Here’s how I’d handle this:

- Implement a visually appealing layout with three stages: Register & Setup, Create and ShareLink, and Receive Payments.
- Build reusable components for each stage, ensuring proper organization within a how-it-works folder in the components directory.
- Add icons or visuals to represent each stage, ensuring they match the Figma design and maintain a consistent style.
- Optimize the layout for responsiveness and accessibility, guaranteeing it works seamlessly across all devices.
- Test for visual consistency and functionality to ensure the section aligns with the design and user expectations.

I aim to complete this task within 24 hours being assigned and setting up my development environment, with my first pull request submitted before 8 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by codeZe-us** [comment]
Can I take this task?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail.
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.

ETA- 2days

**Comment by TheSQLguy** [comment]
So, I will break down the Figma design for the "How it Works" section and create reusable components for each of the three stages: Register & Setup, Create and ShareLink, and Receive Payments. Icons or visuals will be added for each stage to make it clearer. The section will be responsive and accessible across devices, and it will be placed in the how-it-works folder within components for organization.

**Comment by Supa-mega** [comment]
Is this issue still available?

**Comment by emmz3230** [comment]
I'd be happy to do this.


Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will create the how-to section with the content appealing desing amde in the figma design make it respoonsive and using the font u=sed in the design.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe (A Defi startup built on Lisk)
• Scaffold-ETH
• BuidlGuidl
I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by therealemino** [comment]
Can I try solving this issue?

**Comment by Shoetan** [comment]
I’d love to work on this task.

I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Recently contributed to Carbonable PR: https://github.com/Carbonable/contracts-watcher/pull/27   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan.      ETA: 2 days

**Comment by caxtonacollins** [comment]
I’d love to work on this task.

**Comment by kimcascante** [comment]
I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, to disable buttons based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the Figma design and landing page, then create a reusable component and I'll test the changes, and prepare a PR for review.
Happy to contribute!

**Comment by respp** [comment]
Hello! 
I am confident that I can add value to projects focused on component development. I am part of the Dojo community and am excited about the opportunity to contribute to this task and make a significant impact on PayStell.

With my experience as a frontend and full-stack developer, I have a strong understanding of reusable components and responsive design. For the How it Works section, I will analyze the Figma design, implement each stage (Register & Setup, Create and ShareLink, Receive Payments) as a reusable component, and ensure that the section is fully responsive, visually consistent, and accessible, meeting all the established Acceptance Criteria. I am excited to bring my skills to this project and deliver high-quality code.

Thank you for the opportunity!
