### ISSUE TITLE
Create Why Choose PayStell? Section

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-landing#8]
## 📄 Issue Description
Implement the Why Choose PayStell? section of the landing page based on the Figma design. This section highlights the key benefits and features that set PayStell apart.

## 🔍 Steps

1. Analyze the Figma design for the "Why Choose PayStell?" section.
2. See how the components of the current landing page are implemented and created.
3. Create a reusable component for displaying benefits and features.
4. Add icons or visuals to enhance each feature.
5. Ensure proper alignment and spacing for readability and visual appeal.

## ✅ Acceptance Criteria

- The "Why Choose PayStell?" section matches the Figma design.
- Section is fully responsive and accessible.
- Components must be separated in their individual folder per section. In this case, use the why-choose-paystell folder in components.

## 🌎 References
[Figma Design](https://github.com/PayStell/paystell-landing/blob/main/landingPage.md)

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by MarcusDavidG** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
Could I be assigned to this?

**Comment by Michaelkingsdev** [comment]
Let me handle this issue!

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ShantelPeters** [comment]
Could I take over this issue?

**Comment by JamesVictor-O** [comment]
I'm a frontend developer proficient in JavaScript, TypeScript, React.js, and Next.js. With experience in building visually appealing web applications, I'm confident in implementing the 'Why Choose PayStell?' section of the landing page based on the Figma design, using Shadcn UI and Tailwind CSS, with an Eth of 24 hours

**Comment by psychemist** [comment]
Hello, Paystell maintainers!!

I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites, and decentralized applications. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js, Nest.js), Django
Web3: Solidity and Rust.

Here’s how I’d handle this:

- Develop a clean, engaging layout that highlights the key benefits and features from the "Why Choose PayStell?" section.
- Create reusable components for displaying individual benefits or features, keeping them organized in the why-choose-paystell folder within components.
- Add icons or visuals to enhance each feature, ensuring they align with the Figma design and amplify the content.
- Optimize spacing and alignment to improve readability and maintain visual appeal.
- Make the section fully responsive and accessible, ensuring it looks great and functions well on all devices.

I aim to complete this task within 24 hours being assigned and setting up my development environment, with my first pull request submitted before 8 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/ Let me try this one

**Comment by codeZe-us** [comment]
Can I try solving this issue?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by emarc99** [comment]
I am a member of the Web3Bridge coding community, and I have built similar pages recently: https://github.com/emarc99/no-fail.
With my UI/UX and frontend development (React Vite, Tailwind, NextJs) experience, I will create pitch-perfect design and ensure functionality meet the requirement. I will also test and build.
ETA - 2 days

**Comment by davedumto** [comment]
Hi, my name is David, and I am skilled in JavaScript, TypeScript, Tailwind CSS, and ShadCN.
To implement the "Why Choose PayStell?" section, I will analyze the Figma design to create a reusable component for displaying benefits and features. I will enhance each feature with icons or visuals, ensuring proper alignment, spacing, and styling for readability and visual appeal. The components will be fully responsive, accessible, and organized in the why-choose-paystell folder.
ETA: 3 days.
Thank you for considering my application!

**Comment by diegoTech14** [comment]
Hello @MPSxDev  my name is Diego Duarte Fernández, I'm a software engineer from Costa Rica and Dojo Coding member ⛩️, I have experience with technologies like TypeScript, CSS3, JavaScript, Tailwind and Bootstrap. Also I'm maintainer of SafeTrust project which is a security deposit service project. 🤖

I would love to tackle this issue and contribute for your amazing project.

#### Step by step for this issue:
1. I will analyze the Figma design for the "Why Choose PayStell?" section to ensure that I understand the web design and create the section accordingly.
 
2. I'll check the existing components of the current landing page to follow the way that they are implemented.

3. I'll create a reusable component for displaying benefits and features and make it atomic.

 4. I'll add icons or visuals to improve the aspect of the component.

 5. I'll ensure that the component is fully responsive.

Thanks for your consideration.

Best regards,
Diego Duarte Fernández. ✨

**Comment by TheSQLguy** [comment]
So I am new to open source.
Firstlt, I'll analyze the Figma design for the "Why We Stand Out" section, and create a reusable component to show up the distinctive features of PayStell. The component will use visuals, animations, or icons to create an interactive section that remains responsive and accessible on any device. The section is located within the why-we-stand-out folder within components to keep it well-organized.

**Comment by Villarley** [comment]
Hi 👋🏻
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

To tackle this issue:

I’ll analyze the Figma design and existing landing page components.
Create a reusable component for the "Why Choose PayStell?" section, including icons/visuals for each feature.
Ensure the section is responsive, accessible, and matches the design.
Organize components in the why-choose-paystell folder for modularity.
ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by emmz3230** [comment]
Could I be assigned to this?

Is it okay if I tackle this?

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will interpret the design using the Figma design to the satisfaction of the project brand by using the font and images. and any other thing used in the design and making sure it is responsive.

**Comment by Gifftybabe** [comment]
Hi there! I'm excited to apply for the ODHack task of building the "Why Choose PayStell?" section of the landing page.
What I Bring to the Project

Strong React development skills
Experience creating responsive web components
Attention to detail in design implementation
Ability to translate Figma designs into clean, functional code

My Approach
I've already developed a reusable React component that:

Displays key features with icons
Looks great on mobile and desktop
Matches the component structure of the existing landing page
Uses TypeScript for reliable code
Implements a responsive, grid-based layout

Why I'm a Good Fit
I understand the project needs:

Pixel-perfect design matching
Responsive and accessible components
Clean, modular code structure
Quick implementation of the feature section

I'm ready to dive in and create a component that not only looks great but also clearly communicates PayStell's unique benefits.
Looking forward to the opportunity!

**Comment by wheval** [comment]
Can I be assigned to this?

ETA is 1 day.

**Comment by therealemino** [comment]
I’d like to work on this.

**Comment by caxtonacollins** [comment]
Can I jump on this task?

**Comment by diegoTech14** [comment]
Hello @MPSxDev Thanks for the opportunity, I will start ASAP!
